apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - name: log-output
        image: amolmagdum25/log_output_pvc_2.1:2.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PINGPONG_URL
          value: http://pingpong:8089/pingpong
