apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - name: log-output
        image: log-output:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: COUNTER_FILE
          value: /data/counter.txt
        - name: LOG_FILE
          value: /data/log.txt
        volumeMounts:
        - name: shared-data
          mountPath: /data
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: image-claim
