apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-image-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: project-image-cache-pv
