apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo-app
          image: amolmagdum25/todo-frontend:1.0
          ports:
            - containerPort: 6050
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
spec:
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 6050
      targetPort: 6050